version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gin -i run main.go
    tty: true
    depends_on:
      - mysql
    volumes:
      - .:/go/src/github.com/ikotan/go-todo-template
    ports:
      - "3000:3001"
    environment:
      - ENV=develop
  mysql:
    image: mysql:5.7
    command: [--character-set-server=utf8mb4, --collation-server=utf8mb4_general_ci]
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes